import type { LucideIcon } from "lucide-react";
import { AirVent, BadgeCheck, BrickWall, Bug, Building2, Cable, ChefHat, Construction, Droplets, Flower2, Hammer, HandPlatter, HardHat, PaintRoller, PackageCheck, ShieldCheck, Sparkles, UsersRound, Wrench } from "lucide-react";

export type Service = { slug: string; title: string; short: string; description: string; icon: LucideIcon; image: string; category: string };

export const services: Service[] = [
  { slug:"housekeeping", title:"Housekeeping Services", short:"Spotless, healthier workspaces", description:"Daily housekeeping programs that protect hygiene, presentation and productivity.", icon:Sparkles, image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=85", category:"Essential care" },
  { slug:"security", title:"Security Services", short:"Protection you can rely on", description:"Trained guards and site-specific security practices for people, property and peace of mind.", icon:ShieldCheck, image:"https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=1200&q=85", category:"Essential care" },
  { slug:"electrical-maintenance", title:"Electrical Maintenance", short:"Safe, uninterrupted operations", description:"Responsive electrical support, inspections and preventive maintenance for dependable facilities.", icon:Cable, image:"https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=85", category:"Technical care" },
  { slug:"plumbing", title:"Plumbing Services", short:"Every detail working perfectly", description:"Repairs, installations and preventive plumbing maintenance for commercial and residential sites.", icon:Droplets, image:"https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1200&q=85", category:"Technical care" },
  { slug:"hvac-ac", title:"HVAC & AC Maintenance", short:"Comfort, efficiently maintained", description:"AC servicing and HVAC care that keeps your environment comfortable and energy-conscious.", icon:AirVent, image:"https://images.unsplash.com/photo-1581092919535-7146ff1a590f?auto=format&fit=crop&w=1200&q=85", category:"Technical care" },
  { slug:"pest-control", title:"Pest Control", short:"A cleaner, safer environment", description:"Scheduled, discreet pest-control programs tailored to the risks and regulations of your site.", icon:Bug, image:"https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=1200&q=85", category:"Essential care" },
  { slug:"deep-cleaning", title:"Deep Cleaning", short:"A reset for your space", description:"Detailed, high-impact cleaning for handovers, launches, seasonal refreshes and specialist needs.", icon:BadgeCheck, image:"https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=1200&q=85", category:"Essential care" },
  { slug:"building-maintenance", title:"Building & Office Maintenance", short:"Facilities that stay ready", description:"Coordinated upkeep that protects your assets and keeps everyday operations flowing.", icon:Building2, image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85", category:"Technical care" },
  { slug:"civil-renovation", title:"Civil Repair & Renovation", short:"Built better, maintained longer", description:"Thoughtful repair and renovation work delivered with minimum disruption to your operations.", icon:BrickWall, image:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85", category:"Projects" },
  { slug:"carpenter-work", title:"Carpenter Work", short:"Crafted for everyday use", description:"Practical joinery, repairs and fit-outs for workplace, hospitality and residential environments.", icon:Hammer, image:"https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=1200&q=85", category:"Projects" },
  { slug:"painting", title:"Painting Services", short:"A finish that reflects your standards", description:"Interior and exterior painting programs with detail, safety and clean handover built in.", icon:PaintRoller, image:"https://images.unsplash.com/photo-1562259949-a4c9c6f2a91b?auto=format&fit=crop&w=1200&q=85", category:"Projects" },
  { slug:"garden-landscaping", title:"Garden & Landscaping", short:"Greener spaces, better days", description:"Landscape maintenance that makes outdoor spaces feel cared for, welcoming and alive.", icon:Flower2, image:"https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=85", category:"Projects" },
  { slug:"amc", title:"AMC & Annual Maintenance", short:"Planned care, fewer surprises", description:"Annual service plans that organise maintenance and help prevent downtime before it happens.", icon:Wrench, image:"https://images.unsplash.com/photo-1581093458791-9f3c3250e16f?auto=format&fit=crop&w=1200&q=85", category:"Technical care" },
  { slug:"supplies", title:"Facility Supplies & Consumables", short:"The essentials, always ready", description:"Reliable supply of the cleaning and facility consumables that keep teams moving.", icon:PackageCheck, image:"https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=1200&q=85", category:"Operations" },
  { slug:"manpower", title:"Manpower Supply", short:"The right people, on demand", description:"Dependable staffing support, selected and managed to fit your everyday operations.", icon:UsersRound, image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85", category:"Operations" },
  { slug:"caretaker", title:"Caretaker Services", short:"A familiar hand on site", description:"Reliable caretaker support for residential communities, properties and specialist sites.", icon:HandPlatter, image:"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=85", category:"Operations" },
  { slug:"food-supply", title:"Food Supply Services", short:"Hospitality handled with care", description:"Food and hospitality support planned around quality, service standards and your schedule.", icon:ChefHat, image:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=85", category:"Operations" },
  { slug:"event-support", title:"Event Management & Support", short:"Every occasion, expertly supported", description:"Operational event support that makes corporate and institutional gatherings run smoothly.", icon:Construction, image:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85", category:"Operations" }
];

export const industries = ["Corporate Offices", "IT & ITES Companies", "Hospitals & Healthcare", "Schools & Colleges", "Apartments & Gated Communities", "Hotels & Restaurants", "Factories & Industries", "Government Offices", "Shopping Malls", "Events & Institutions"];
