import type { LucideIcon } from "lucide-react";
import { Armchair, BadgeCheck, BrickWall, Building2, Cable, ChefHat, Construction, Droplets, Hammer, HandPlatter, HardHat, PaintRoller, ShieldCheck, Sparkles, UsersRound, Wrench } from "lucide-react";
export type Service={slug:string;title:string;short:string;description:string;icon:LucideIcon;image:string;category:string;items?:string[]};
export const services:Service[]=[
{slug:"integrated-facility-management",title:"Integrated Facility Management",short:"One accountable partner for your facility",description:"Coordinated facility management that brings people, processes, maintenance and everyday operations together under one professional point of contact.",icon:Building2,image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85",category:"Integrated solutions"},
{slug:"housekeeping-cleaning",title:"Housekeeping & Cleaning Services",short:"Consistently clean, healthy workspaces",description:"Structured daily, periodic and deep-cleaning programs designed around the hygiene, presentation and operational needs of your property.",icon:Sparkles,image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=85",category:"Essential services"},
{slug:"painting-wall-finishing",title:"Painting & Wall Finishing Works",short:"Finishes that reflect your standards",description:"Professional interior and exterior painting, surface preparation and wall finishing for commercial, institutional and residential sites.",icon:PaintRoller,image:"https://images.unsplash.com/photo-1562259949-a4c9c6f2a91b?auto=format&fit=crop&w=1200&q=85",category:"Maintenance works"},
{slug:"carpentry-interior-maintenance",title:"Carpentry & Interior Maintenance",short:"Practical care for every interior",description:"Reliable carpentry repairs, interior upkeep and fit-out support that keep workspaces and properties looking and functioning their best.",icon:Armchair,image:"https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=1200&q=85",category:"Maintenance works"},
{slug:"electrical-maintenance",title:"Electrical Maintenance Works",short:"Safe, uninterrupted operations",description:"Planned electrical maintenance, repairs and inspections delivered with safety, reliability and minimal disruption in mind.",icon:Cable,image:"https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=85",category:"Technical maintenance"},
{slug:"plumbing-water-maintenance",title:"Plumbing & Water Maintenance",short:"Every system working smoothly",description:"Preventive and responsive plumbing, sanitary and water-maintenance support for commercial and residential properties.",icon:Droplets,image:"https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1200&q=85",category:"Technical maintenance"},
{slug:"civil-maintenance-repairs",title:"Civil Maintenance & Repair Works",short:"Built to keep performing",description:"Practical civil repairs and maintenance support that protect your property, minimise disruption and extend asset life.",icon:BrickWall,image:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85",category:"Maintenance works"},
{slug:"welding-metal-fabrication",title:"Welding & Metal Fabrication Works",short:"Precision-built metal solutions",description:"Professional welding and metal fabrication support for repairs, alterations and site-specific property requirements.",icon:Hammer,image:"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=85",category:"Fabrication works"},
{slug:"ms-steel-shed-fabrication",title:"MS / Steel Shed Fabrication",short:"Functional structures, professionally delivered",description:"MS and steel shed fabrication tailored to the operational, storage and protection needs of your site.",icon:Construction,image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85",category:"Fabrication works"},
{slug:"roofing-shed-installation",title:"Roofing Sheet / Shed Installation & Replacement",short:"Reliable protection from the top down",description:"Roofing sheet and shed installation, repair and replacement support for facilities that need durable protection.",icon:HardHat,image:"https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=85",category:"Fabrication works"},
{slug:"car-parking-sheds",title:"Car Parking Shed Works",short:"Covered parking, thoughtfully executed",description:"Durable car parking shed design, fabrication and installation to protect vehicles and improve site convenience.",icon:ShieldCheck,image:"https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=1200&q=85",category:"Fabrication works"},
{slug:"gates-grills-handrails",title:"Gates, Grills, Handrails & Staircase Fabrication",short:"Safety and function, built in",description:"Custom fabrication for gates, grills, handrails and staircases with practical quality and reliable finishing.",icon:BadgeCheck,image:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85",category:"Fabrication works"},
{slug:"food-catering",title:"Food Supply & Catering Support",short:"Hospitality support with care",description:"Flexible food supply and catering support for workplaces, institutions, functions and day-to-day hospitality requirements.",icon:ChefHat,image:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=85",category:"Support services"},
{slug:"event-support",title:"Event Organisation & Maintenance Support",short:"Dependable support for every occasion",description:"Operational event support that helps corporate, institutional and community gatherings run smoothly from setup to close.",icon:HandPlatter,image:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85",category:"Support services"},
{slug:"general-building-maintenance",title:"General Building Maintenance",short:"Everyday care for your property",description:"Coordinated property upkeep across routine repairs, inspections and general maintenance requirements.",icon:Wrench,image:"https://images.unsplash.com/photo-1581093458791-9f3c3250e16f?auto=format&fit=crop&w=1200&q=85",category:"Integrated solutions"},
{slug:"amc",title:"Annual Maintenance Contracts (AMC)",short:"Planned maintenance, lasting confidence",description:"A structured Annual Maintenance Contract for routine inspections, preventive maintenance, repairs and ongoing facility support.",icon:BadgeCheck,image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85",category:"Integrated solutions",items:["Routine inspection schedules","Preventive maintenance planning","Priority repair support","Ongoing facility coordination"]},
{slug:"corporate-industrial-manpower",title:"Corporate & Industrial Manpower Supply",short:"The capable workforce your operations need",description:"Professionally managed workforce supply for corporate and industrial environments, selected to meet your operational requirements.",icon:UsersRound,image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=85",category:"Support services",items:["Housekeeping Staff","Cleaning Staff","Facility Support Staff","Office Support Staff","Helpers","Maintenance Support Staff","Skilled / Semi-skilled Workforce"]},
{slug:"residential-painting",title:"Residential House Painting & Finishing",short:"A more considered finish for home",description:"Professional house painting and finishing solutions that refresh, protect and elevate every residential space.",icon:PaintRoller,image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",category:"Maintenance works",items:["Interior House Painting","Exterior House Painting","Wall Putty & Surface Preparation","Primer & Painting","Ceiling Painting","Texture & Decorative Painting","Repainting & Renovation","Doors & Windows Painting","Gates, Grills & Railings Painting","Minor Crack & Surface Repair","Protective / Waterproof Coating"]}
];
export const industries=["Corporate Offices","Commercial Buildings","Residential Properties","Educational Institutions","Hospitals & Healthcare","Industrial Facilities","Retail & Commercial Spaces","Hotels & Hospitality","Property Management"];
export const phone="9700012237", secondaryPhone="8500229978", whatsapp="9700012237", email="saipavanoffical@gmail.com", maps="https://maps.app.goo.gl/8pnmLhsqwSgJSMXL8";
export const whatsappUrl=(service?:string)=>`https://wa.me/91${whatsapp}?text=${encodeURIComponent(`Hello Sai Pavan Integrated Facility Services, I would like to enquire about ${service || "your facility services"}.`)}`;
